version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3303:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_TCP_PORT: 3303

  wordpress:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3303
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_VERSION: 6.6
      PLUGIN_DIR: /var/www/html/wp-content/plugins/accredible-learndash-add-on
      ACCREDIBLE_LEARNDASH_API_ENDPOINT:
    volumes:
      - wordpress_data:/var/www/html
      # Install Accredible plugin by default
      - ".:/var/www/html/wp-content/plugins/accredible-learndash-add-on"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    ports:
      - "8082:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db:3303

volumes:
  db_data: {}
  wordpress_data: {}
